--
-- Refer to the wiki for more information.

--
-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
--

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
  output = "",
  mode = "preferred",
  position = "auto",
  scale = "1",
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- windowrulev2=nofullscreenrequest,^(mpv)$
-- windowrulev2=noblur,class:^()$,title:^()$

-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

local mainMod = "SUPER"

hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("ghostty"))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("wpctl set-mute -p $(hyprctl activewindow -j | jq '.pid') toggle"))
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy"))
hl.bind(mainMod .. " + SHIFT + Print",
  hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" ~/Pictures/$(date +%Y-%m-%d_%H-%M-%S).png"))
hl.bind(mainMod .. " + t", hl.dsp.group.toggle())

hl.bind(mainMod .. " + F10", hl.dsp.exec_cmd("wf-recorder --audio --file=/run/mount/recordings/$(uuidgen).mkv"))
hl.bind(mainMod .. " + SHIFT + F10", hl.dsp.exec_cmd("killall wf-recorder"))

hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + SHIFT + mouse_up",
  hl.dsp.exec_cmd(
    "hyprctl keyword cursor:zoom_factor $(awk \"BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') - 0.5}\")"))
hl.bind(mainMod .. " + SHIFT + mouse_down",
  hl.dsp.exec_cmd(
    "hyprctl keyword cursor:zoom_factor $(awk \"BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') + 0.5}\")"))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.config({
  input = {
    kb_layout = "us",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",
    follow_mouse = 2,
    touchpad = {
      natural_scroll = false,
    },
    sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
  },
  general = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 3,
    gaps_out = 5,
    border_size = 1,
    col = {
      active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
      inactive_border = "rgba(595959aa)",
    },
    no_focus_fallback = true,
    layout = "dwindle",
  },
  decoration = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 0,
    inactive_opacity = 0.95,
  },
  animations = {
    enabled = false,
    -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    -- bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    -- animation = windows, 1, 7, myBezier
    -- animation = windowsOut, 1, 7, default, popin 80%
    -- animation = border, 1, 10, default
    -- animation = fade, 1, 7, default
    -- animation = workspaces, 1, 6, default
  },
  dwindle = {
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    -- pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true, -- you probably want this
  },
  group = {
    groupbar = {
      render_titles = false,
    },
  },
  master = {
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  },
  gestures = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    -- workspace_swipe = off
  },
  -- Example per-device config
  -- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
  -- device:epic mouse V1 {
  -- sensitivity = -0.5
  -- }
  -- Example windowrule v1
  -- windowrule = float, ^(kitty)$
  -- Example windowrule v2
  -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
  -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
  -- See https://wiki.hyprland.org/Configuring/Keywords/ for more
  -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
  -- bind = $mainMod, E, exec, dolphin
  -- bind = $mainMod, S, togglesplit, # dwindle
  -- bind = $mainMod, Print, exec, XDG_CURRENT_DESKTOP=sway flameshot gui --path /run/mount/photos/ScreenShots/
  -- bind = $mainMod SHIFT, Print, exec, XDG_CURRENT_DESKTOP=sway flameshot gui --clipboard
  -- Move focus with mainMod + arrow keys
  -- Move focused window with mainMod SHIFT + arrow keys
  -- Switch workspaces with mainMod + [0-9]
  -- Move active window to a workspace with mainMod + SHIFT + [0-9]
  -- Scroll through existing workspaces with mainMod + scroll
  -- Magnify screen
  -- Move/resize windows with mainMod + LMB/RMB and dragging
  -- Execute your favorite apps at launch
})

hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("waybar")
  hl.exec_cmd("hyprpaper")
  -- hl.exec_cmd("qbittorrent")
end)
